#!/bin/bash
XVDAP1=/dev/xvda1
if [[ "$1" == '--device' ]] && [[ "$2" == "$XVDAP1" ]]; then
  case x"$3" in
    x--target=partmap)
      echo "msdos"
      exit 0;;
  esac
  :
fi

if [[ "$1" == '--target=device' ]]; then
  case x"$2" in
    x/)
      echo "$XVDAP1"
      exit 0;;
    x/boot)
      echo "$XVDAP1"
      exit 0;;
  esac
fi

exec /tmp/grub-probe $@
